#!/bin/bash


SITE_NAME=${1%/}
ARG_1=$2
ARG_2=$3

if [ ${ARG_1: -4} == ".tar" ]
        then
ARCHIVE=$ARG_1
        else
BACKUP=$ARG_1
fi

if [ ${ARG_2: -4} == ".sql" ]
        then
BACKUP=$ARG_2
        else
ARCHIVE=$ARG_2
fi


if [ [ "${ARCHIVE: -4}" -ne ".tar" -a  "${BACKUP: -4}" -ne ".sql" ] ]
then
        echo "check arguments names"
        exit
else
#       mv $SITE_NAME $SITE_NAME.old

        tar -xvf $ARCHIVE $SITE_NAME

        WPDBNAME=`grep DB_NAME $SITE_NAME.old/wp-config.php | cut -d \' -f 4`
        WPDBUSER=`grep DB_USER $SITE_NAME.old/wp-config.php | cut -d \' -f 4`
        WPDBPASS=`grep DB_PASSWORD $SITE_NAME.old/wp-config.php | cut -d \' -f 4`
        HOST_PORT=`grep DB_HOST $SITE_NAME.old/wp-config.php | cut -d \' -f 4`

        mysql -uroot -e "CREATE DATABASE $WPDBNAME"

if [ $HOST_PORT == "('DB_HOST', 'localhost')" ]
then
        mysql -p -u$WPDBUSER --password=$WPDBPASS $WPDBNAME < $BACKUP
else
        mysql -p -u$WPDBUSER --password=$WPDBPASS --host=$HOST_PORT $WPDBNAME < $BACKUP
fi

fi
